### ISSUE TITLE
QoS

### ISSUE THREAD

**Issue by derritter88** [jellyfin/jellyfin-docs#258]
Hi there,

I've moved from Plex to Jellyfin as I prefer the FOSS approach.
I just asked myself how a proper QoS could be configured?
So far I managed to create a policy according to the ports I have found here: [https://jellyfin.org/docs/general/networking/index.html](Jellyfin Networking).

Any proper solutions/ideas?

**Comment by hayer** [comment]
Good documentation is important. To create good documentation the bits have to be relevant to the product. I'm having a hard time justifying that QoS is related to Jellyfin.

For instance, the reverse proxy is there because it is used very often, people often have problems with it, and there are specific Jellyfin settings.

QoS is used very seldom, not very related other than ports and UPnP - which you should already know if you are setting it up. This information is easily obtainable within 5 minutes of googling.

But I'll leave this for now for someone else to comment on.

**Comment by MrTimscampi** [comment]
The issue I see is that QoS is incredibly generic, and shouldn't be done by users who know nothing about how QoS works or is.

All you basically need is the list of ports, which are already in the documentation (and some you can infer like 80/tcp and 443/tcp for the web client).

The rest is heavily dependent on what you want to do, your networking hardware and topology, your configuration, etc.

There's really no "one size fits all" for this, pretty much like for reverse proxies (and there's been a bit of discussions about reworking the reverse proxies pages recently due to that).

Imho, it's outside of the scope of Jellyfin to provide a step by step on what QoS is and how to implement it. The documentation needs to stay relevant to Jellyfin and I see nothing directly related to Jellyfin for this topic, aside from a ports list (which is already documented).

**Comment by derritter88** [comment]
Okay so let's leave it as it is currently.
